repos:
- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v2.5.0
  hooks:
  - id: trailing-whitespace
  - id: check-added-large-files
  - id: check-ast
  - id: check-json
  - id: check-merge-conflict
  - id: check-xml
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: requirements-txt-fixer
  - id: check-toml
  - id: fix-encoding-pragma
  - id: mixed-line-ending
    args: ['--fix=auto']

- repo: git://github.com/guykisel/prospector-mirror
  rev: '7ff847e779347033ebbd9e3b88279e7f3a998b45'
  hooks:
  - id: prospector
    pass_filenames: false

- repo: https://github.com/psf/black
  rev: stable
  hooks:
    - id: black
      language_version: python3.7

- repo: https://github.com/pre-commit/mirrors-isort
  rev: v4.3.4
  hooks:
  - id: isort
