repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
        require_serial: true
      - id: check-added-large-files
        name: Check for added large files
        entry: check-added-large-files
        language: system
      - id: check-toml
        name: Check Toml
        entry: check-toml
        language: system
        types: [toml]
      - id: check-yaml
        name: Check Yaml
        entry: check-yaml
        language: system
        types: [yaml]
      - id: end-of-file-fixer
        name: Fix End of Files
        entry: end-of-file-fixer
        language: system
        types: [text]
        stages: [commit, push, manual]
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
        require_serial: true
      - id: reorder-python-imports
        name: Reorder python imports
        entry: reorder-python-imports
        language: system
        types: [python]
        args: [--application-directories=src]
      - id: trailing-whitespace
        name: Trim Trailing Whitespace
        entry: trailing-whitespace-fixer
        language: system
        types: [text]
        stages: [commit, push, manual]
      - id: debug-statements
        name: debug-statements
        entry: debug-statements
        language: system
        types: [python]
      - id: check-merge-conflict
        name: check-merge-conflict
        entry: check-merge-conflict
        language: system
        types: [text]
      - id: check-json
        name: check-json
        entry: check-json
        language: system
        types: [text]
      - id: check-ast
        name: check-ast
        entry: check-ast
        language: system
        types: [python]
      - id: fix-encoding-pragma
        name: fix-encoding-pragma
        entry: fix-encoding-pragma
        language: system
        types: [python]
      - id: mixed-line-ending
        name: mixed-line-ending
        entry: mixed-line-ending
        language: system
        types: [text]
        args: ["--fix=auto"]
  - repo: https://github.com/prettier/pre-commit
    rev: v2.1.2
    hooks:
      - id: prettier
